### ISSUE TITLE
visitFor chưa có expr3

### ISSUE THREAD

**Issue by hoang-himself** [CaptainCuong/HCMUT-PPL#2]
https://github.com/CaptainCuong/HCMUT-PPL/blob/7fe48898fac808c3e96c9debab9474e861b0e210/assignment3_update/initial/src/main/d96/checker/StaticCheck.py#L412-L425

Mục 6.4 của spec nói expr1, expr2, expr3 phải là IntType mà không đề cập đến scalar variable. Chỗ này phải xem lại type coercion.

**Comment by CaptainCuong** [comment]
ok ô để t sửa
